config/routes.rb
Elevation::Application.routes.draw do
  resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trips_controller.rb
require 'elevation.rb'

class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    elevation = ElevationAPI.new :samples => 40, :path => "#{@trip.xp},#{@trip.yp}|#{@trip.xk},#{@trip.yk}"
	
    @img_link = elevation.get_chart :chtt => "#{@trip.name}", :chxl => "0:|profil trasy"
    @min = elevation.get_min
    @max = elevation.get_max
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <%= csrf_meta_tag %>

  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
       Remove this if you use the .htaccess -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Tatry</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
  <!-- CSS: implied media="all" -->
  <%= stylesheet_link_tag "application" %>

  <!-- More ideas for your <head> here: h5bp.com/docs/#head-Tips -->

  <!-- All JavaScript at the bottom, except for Modernizr and Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag "modernizr" %>


</head>
<body>
<div id="container">
<div id="header">

  <h1><a href="#">Niebezpieczne trasy</a></h1>
  <h2>na terenie Tatr Polskich</h2>

  <ul id="menu">
    <li id="tab_01"><a href="http://localhost:3000/trips/">Start</a></li>
    <li id="tab_02"><a href="http://localhost:3000/trips/new">Nowa</a></li>
    <li id="tab_03"><a href="http://www.google.pl/search?q=tatry&hl=pl&prmd=imvnsb&source=lnms&tbm=isch&ei=8PK4TrahD9CM4gSiqtCQCA&sa=X&oi=mode_link&ct=mode&cd=2&ved=0CBkQ_AUoAQ&biw=1300&bih=656&sei=%208vK4TuV9qOHhBN3HpfcH">Galeria</a></li>
  </ul>

</div>
<div id="content">
  <div id="main_column">
    <div class="entry">
      <span class="date"><%= Time.now.strftime("%Y-%m-%d %H:%M") %></span>

  <%= yield %> <!--! end of #container -->
  <%= javascript_include_tag "application" %>
  <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

      <div class="entry_footer">

      </div>
   </div>
  </div>

  <div id="side_panel">
    <div id="search_box"></div>
    <form method="get" action="http://www.google.com/search">

      <div id="search_form">
        <div id="search_field"> 
          <label for="search_text"> 
            <span id="search_left"></span> 
            <input id="search_text" name="q" type="text" /> 
            <span id="search_right"></span>
          </label>
        </div>

        <div id="search_button"> 
          <input src="images/search_button.gif" type="image" name="sa" />
        </div>
        <input type="hidden" name="sitesearch" value="" />
        <input type="hidden" name="domains" value="" />
        <input type="hidden" name="hl" value="pl" />
      </div>
    </form>

    <div id="archives_box">
      <div id="archives_content">
        <h4>Ważne!!</h4>
        <ul>
          <li>TORP 601 100 300</a></li>
          <li>TORP 985</a></li>
        </ul>
      <span id="archives_footer"></span>
     </div>
    </div>


<div id="archives_box">
      <div id="archives_content">
        <h4>Nie zapomnij!!</h4>
        <ul>
          <li>Solidne obuwie</a></li>
	  <li>Mapa</a></li>
	  <li>Deszczak</a></li>
          <li>Ciepłe ubranie</a></li>
	  <li>Picie, jedzenie</a></li>
	  <li>Środki opatrunkowe, leki</a></li>
        </ul>
      <span id="archives_footer"></span>
     </div>
    </div>

    <div class="list_box">
      <h4>Polecane strony</h4>
        <ul>
          <li><a href="http://www.tatry.info.pl/"> Internetowy przewodnik po Tatrach </a></li>
          <li><a href="http://www.tatry.info.pl/">Tatrzański Serwis Informacyjny </a></li>
          <li><a href="http://www.tpn.pl/">TPN</a></li>
          <li><a href="http://www.promocja.zakopane.pl/">Biuro Promocji Zakopanego</a></li>
	  <li><a href="http://www.promocja.zakopane.pl/">TOPR</a></li>
        </ul>
    </div>
  
    <div id="design">
    </div>
  </div>
  <div class="clear"></div>
</div>
</div>
<div id="footer"></div>
</body>
</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Poczatkowy_punkt_po_wspolrz_X  %><br />
    <%= f.text_field :xp %>
  </div>
  <div class="field">
    <%= f.label :Poczatkowy_punkt_po_wspolrz_Y %><br />
    <%= f.text_field :yp %>
  </div>
  <div class="field">
    <%= f.label :Koncowy_punkt_po_wspolrz_X  %><br />
    <%= f.text_field :xk %>
  </div>
  <div class="field">
    <%= f.label :Koncowy_punkt_po_wspolrz_Y  %><br />
    <%= f.text_field :yk %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h3>Edytuj trase</h3>

<%= render 'form' %>

<%= link_to 'Pokaz', @trip %> |
<%= link_to 'Powrot', trips_path %>

app/views/trips/index (kopia).html.erb
<h3>Lista niebezpiecznych tras w Tatrach Polskich</h3>

<table>
  <tr>
    <th>Nazwa trasy</th>
    <th>Punkt poczatkowy po wspolrz. x</th>
    <th>Punkt poczatkowy po wspolrz. y</th>
    <th>Punkt koncowy po wspolrz. x</th>
    <th>Punkt koncowy po wspolrz. y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.name %></td>
    <td><%= trip.xp %></td>
    <td><%= trip.yp %></td>
    <td><%= trip.xk %></td>
    <td><%= trip.yk %></td>
    <td><%= link_to 'Pokaz', trip %></td>
    <td><%= link_to 'Edytuj', edit_trip_path(trip) %></td>
    <td><%= link_to 'Usun', trip, confirm: 'Na pewno?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nowa trasa', new_trip_path %>

app/views/trips/index.html.erb
<h3>Lista niebezpiecznych tras w Tatrach Polskich</h3>

<table>
  <tr>
    <th>Nazwa trasy</th>

    <th>  </th>
    <th>  </th>
    <th>  </th>
  </tr>


<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.name %></td>

    <tr><td><%= link_to 'Pokaz', trip %></td></tr>
    <tr><td><%= link_to 'Edytuj', edit_trip_path(trip) %></td></tr>
    <tr><td><%= link_to 'Usun', trip, confirm: 'Na pewno?', method: :delete %></td></tr>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nowa trasa', new_trip_path %>

app/views/trips/new.html.erb
<h3>Nowa trasa</h3>

<%= render 'form' %>

<%= link_to 'Powrot', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa trasy:</b>
  <%= @trip.name %>
</p>

<p>
  <b>Punkt poczatkowy trasy po wspolrzednych x:</b>
  <%= @trip.xp %>
</p>

<p>
  <b>Punkt poczatkowy trasy po wspolrzednych y:</b>
  <%= @trip.yp %>
</p>

<p>
  <b>Punkt koncowy trasy po wspolrzednych x:</b>
  <%= @trip.xk %>
</p>

<p>
  <b>Punkt koncowy trasy po wspolrzednych y:</b>
  <%= @trip.yk %>
</p>

<%= image_tag @img_link %>

<%= image_tag"http://maps.google.com/maps/api/staticmap?markers=#{@trip.xp},#{@trip.yp}|#{@trip.xk},#{@trip.yk}&path=#{@trip.xp},#{@trip.yp}|#{@trip.xk},#{@trip.yk}&size=500x300&sensor=false"
%>

<p>
Minimalna wysokosc n.p.m.: <%= @min %> 
</p>
<p>
Maksymalna wysokosc n.p.m. <%= @max %>
</p>

<%= link_to 'Edytuj', edit_trip_path(@trip) %> |
<%= link_to 'Powrot', trips_path %>